In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
genome2temp = pd.read_csv('/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/metric_tables/renamed_files.txt', sep='\t', header=None)
genome2temp = genome2temp.dropna().apply(lambda row: pd.Series(index=['temp', 'genome'],
                                       data=[row[0].split('_bit')[0].split('_temp_')[-1],
                                            row[1].split('/')[-1].split('_closed')[0]]), axis=1)

In [4]:
genome2temp = genome2temp.set_index('genome')['temp']

In [5]:
genome2temp

genome
GB_GCA_000016765.1    30.0
GB_GCA_000283575.1    30.0
GB_GCA_000376885.1    37.0
GB_GCA_000242235.1    37.0
GB_GCA_001054945.1    37.0
                      ...
RS_GCF_905397275.1    30.0
RS_GCF_907163105.1    30.0
RS_GCF_905397435.1    27.0
RS_GCF_910593845.1    30.0
RS_GCF_907163265.1    30.0
Name: temp, Length: 9341, dtype: object

In [6]:
gtdb_md = pd.read_csv('/data/mhoffert/genomes/GTDB_r214.1/bac120_metadata.tsv.gz', sep='\t', index_col=0)

/tmp/ipykernel_3080720/1994908607.py:1: DtypeWarning: Columns (61,63,65,74,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  gtdb_md = pd.read_csv('/data/mhoffert/genomes/GTDB_r214.1/bac120_metadata.tsv.gz', sep='\t', index_col=0)

In [7]:
gtdb_md.head()

,ambiguous_bases,checkm_completeness,checkm_contamination,checkm_marker_count,checkm_marker_lineage,checkm_marker_set_count,checkm_strain_heterogeneity,coding_bases,coding_density,contig_count,...,ssu_silva_blast_align_len,ssu_silva_blast_bitscore,ssu_silva_blast_evalue,ssu_silva_blast_perc_identity,ssu_silva_blast_subject_id,ssu_silva_taxonomy,total_gap_length,trna_aa_count,trna_count,trna_selenocysteine_count
accession,,,,,,,,,,,,,,,,,,,,,
RS_GCF_001206855.1,14,99.60,0.91,761,g__Streptococcus (UID584),238,50.00,1827337,86.246727,77,...,1543,2844,0,99.935,CP028436.1781495.1783046,Bacteria;Firmicutes;Bacilli;Lactobacillales;St...,21,19,35,0
RS_GCF_001108865.1,13,99.39,0.34,761,g__Streptococcus (UID584),238,33.33,1852015,86.277715,51,...,1543,2844,0,99.935,AKVY01000001.1976120.1977665,Bacteria;Firmicutes;Bacilli;Lactobacillales;St...,0,19,38,0
RS_GCF_000730125.1,30,100.00,0.92,476,f__Bifidobacteriaceae (UID1462),217,0.00,2212698,86.271453,45,...,1522,2811,0,100,CP008885.1576966.1578495,Bacteria;Actinobacteriota;Actinobacteria;Bifid...,619,19,55,0
RS_GCF_000950275.1,0,99.45,0.53,921,f__Vibrionaceae (UID4865),366,0.00,4128151,84.994806,57,...,655,1210,0,100,KY272023.1.1437,Bacteria;Proteobacteria;Gammaproteobacteria;En...,0,17,77,1
RS_GCF_000468955.1,0,100.00,0.00,472,o__Lactobacillales (UID543),265,0.00,2107260,86.823994,1,...,1545,2848,0,99.935,CP003157.2105633.2107180,Bacteria;Firmicutes;Bacilli;Lactobacillales;St...,0,19,60,0

In [11]:
# get the bacillus clade 
merged = pd.merge(genome2temp, gtdb_md['gtdb_taxonomy'].apply(lambda x: x.split(';')[-2]).rename('Genus'),
        left_index=True, right_index=True)

In [12]:
merged[merged['Genus'].str.contains('Bacillus')]

                    temp           Genus
RS_GCF_000161455.1  30.0   g__Bacillus_A
RS_GCF_000262045.1  37.0     g__Bacillus
RS_GCF_000262755.1  45.0   g__Bacillus_Z
RS_GCF_000299035.1  30.0   g__Bacillus_A
RS_GCF_000380245.2  37.0  g__Bacillus_AD
RS_GCF_000430765.1  30.0  g__Bacillus_AI
RS_GCF_000473245.1  37.0  g__Bacillus_AB
RS_GCF_000615945.1  33.0  g__Bacillus_AT
RS_GCF_000712595.1  30.0   g__Bacillus_A
RS_GCF_000715205.1  28.0     g__Bacillus
RS_GCF_001050115.1  55.0   g__Bacillus_O
RS_GCF_001274935.1  33.0  g__Bacillus_AG
RS_GCF_001278705.1  30.0     g__Bacillus
RS_GCF_001307105.1  25.0     g__Bacillus
RS_GCF_001584325.1  33.0     g__Bacillus
RS_GCF_001590835.1  30.0   g__Bacillus_A
RS_GCF_001636425.1  32.0  g__Bacillus_AE
RS_GCF_001644195.2  33.0  g__Bacillus_BL
RS_GCF_001742425.1  30.0  g__Bacillus_AV
RS_GCF_001884065.1  28.0   g__Bacillus_A
RS_GCF_002019595.1  28.0  g__Bacillus_BA
RS_GCF_002019705.1  30.0   g__Bacillus_H
RS_GCF_002019765.1  28.0   g__Bacillus_H
RS_GCF_002746455.1  28.0   g__Bacillus_A
RS_GCF_002863585.1  30.0  g__Bacillus_AI
RS_GCF_003073175.1  30.0  g__Bacillus_BN
RS_GCF_003515685.1  29.0   g__Bacillus_D
RS_GCF_003581585.1  37.0  g__Bacillus_BM
RS_GCF_004340465.1  33.0  g__Bacillus_AZ
RS_GCF_005747095.1  28.0  g__Bacillus_BR
RS_GCF_007725405.1  30.0   g__Bacillus_H
RS_GCF_009466385.1  45.0  g__Bacillus_BN
RS_GCF_010882125.1  28.0  g__Bacillus_BN
RS_GCF_014207535.1  30.0  g__Bacillus_BD
RS_GCF_014712675.1  30.0  g__Bacillus_AD
RS_GCF_016907895.1  28.0   g__Bacillus_H
RS_GCF_016908495.1  30.0  g__Bacillus_BW
RS_GCF_016908875.1  29.0  g__Bacillus_BX
RS_GCF_019749255.1  29.0  g__Bacillus_AZ
RS_GCF_900109925.1  28.0  g__Bacillus_AZ
RS_GCF_900111815.1  30.0  g__Bacillus_AZ
RS_GCF_900207585.1  37.0  g__Bacillus_BF

In [16]:
merged.groupby('Genus').apply(lambda x: float(x['temp'].max()) - float(x['temp'].min())).sort_values()

Genus
g__Psychroflexus      -18.0
g__Carnobacterium_A   -16.0
g__Octadecabacter     -16.0
g__Polaribacter       -11.0
g__Tenacibaculum       -6.0
                       ...
g__Flavobacterium      26.0
g__Marinobacter        26.0
g__Thermochromatium    29.0
g__Maribacter          31.0
g__Deinococcus         35.0
Length: 2973, dtype: float64

In [18]:
gtdb_md.loc[merged[merged.Genus.eq('g__Deinococcus')].index, 'gtdb_taxonomy'].apply(lambda x: x.split(';')[-1])

RS_GCF_000020685.1             s__Deinococcus deserti
RS_GCF_000190555.1       s__Deinococcus proteolyticus
RS_GCF_000196275.1        s__Deinococcus geothermalis
RS_GCF_000252445.1           s__Deinococcus gobiensis
RS_GCF_000378445.1           s__Deinococcus aquatilis
RS_GCF_000381345.1          s__Deinococcus apachensis
RS_GCF_000482805.1             s__Deinococcus murrayi
RS_GCF_000599865.1           s__Deinococcus phoenicis
RS_GCF_000701425.1             s__Deinococcus frigens
RS_GCF_000701405.1            s__Deinococcus marmoris
RS_GCF_001007995.1                s__Deinococcus soli
RS_GCF_001485435.1             s__Deinococcus grandis
RS_GCF_001507665.1       s__Deinococcus actinosclerus
RS_GCF_001644565.1            s__Deinococcus puniceus
RS_GCF_002198095.1             s__Deinococcus indicus
RS_GCF_002869765.1          s__Deinococcus planocerae
RS_GCF_002897375.1              s__Deinococcus aerius
RS_GCF_002901445.1           s__Deinococcus koreensis
RS_GCF_003173015.1       s__Deinococcus irradiatisoli
RS_GCF_003444775.1               s__Deinococcus ficus
RS_GCF_003860465.1     s__Deinococcus psychrotolerans
RS_GCF_004634215.1           s__Deinococcus fonticola
RS_GCF_004758605.1        s__Deinococcus metallilatus
RS_GCF_007280555.1        s__Deinococcus detaillensis
RS_GCF_009377345.1          s__Deinococcus terrestris
RS_GCF_009982895.1       s__Deinococcus alpinitundrae
RS_GCF_011067105.1       s__Deinococcus wulumuqiensis
RS_GCF_014201875.1                s__Deinococcus humi
RS_GCF_014201885.1           s__Deinococcus budaensis
RS_GCF_014646915.1       s__Deinococcus aquiradiocola
RS_GCF_014647055.1           s__Deinococcus aerolatus
RS_GCF_014647075.1          s__Deinococcus aerophilus
RS_GCF_014647435.1       s__Deinococcus radiotolerans
RS_GCF_014647655.1          s__Deinococcus malanensis
RS_GCF_014648095.1               s__Deinococcus ruber
RS_GCF_014648115.1          s__Deinococcus seoulensis
RS_GCF_014648135.1           s__Deinococcus sedimenti
RS_GCF_014653275.1              s__Deinococcus piscis
RS_GCF_900109185.1    s__Deinococcus reticulitermitis
RS_GCF_900176165.1           s__Deinococcus hopiensis
Name: gtdb_taxonomy, dtype: object

In [ ]:
Bio.codonalign.codonseq.CodonSeq()

In [ ]:
Bio.codonalign.codonseq.cal_dn_ds()